update workflow

diff --git a/.github/workflows/django.yml b/.github/workflows/django.yml
--- a/.github/workflows/django.yml
+++ b/.github/workflows/django.yml
@@ -24,7 +24,23 @@ jobs:
     - name: Install Dependencies
       run: |
         python -m pip install --upgrade pip
-        pip install -r ./requirements.txt
-    - name: Run Tests
+    #- name: Run Tests
+    #  run: |
+    #    python ./bytebelt/manage.py test
+    - name: Start Django Server with Docker  
       run: |
-        python manage.py test
+        cd ./bytebelt/
+        docker-compose up -d
+        sleep 30
+        docker exec -it bytebelt_web_1 python manage.py migrate
+
+    - name: Test endpoint
+      run: |
+        site_online=$(curl -o /dev/null -s -w "%{http_code}\n" http://localhost:8000)
+        if [[ "$site_online" =~ ^4 ]] || [[ "$site_online" =~ ^5 ]]; then
+          echo "Test Failed $site_online"
+          exit 1
+        else
+          echo "Test Ok $site_online"
+        fi
+      
