add deployement with azure and allow all host

diff --git a/.github/workflows/pushImage.yml b/.github/workflows/pushImage.yml
--- a/.github/workflows/pushImage.yml
+++ b/.github/workflows/pushImage.yml
@@ -15,18 +15,28 @@ jobs:
       - name: Login to Docker Hub
         uses: docker/login-action@v1
         with:
-          username: ${{ secrets.DOCKER_USERNAME }}
-          password: ${{ secrets.DOCKERHUB_TOKEN }}
+          username: aperano
+          password: dckr_pat_tOyTOPXz3VYOUy_cnmCo5AlQ6lk
 
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v1
 
-      - name: Build and push to Docker Hub
+      - name: Build and push to Docker Compose Hub
         uses: docker/build-push-action@v5
         with:
-          context: .
+          context: ./bytebelt
           push: true
-          tags: ${{ secrets.DOCKER_USERNAME }}/bytebelt:latest
+          tags: aperano/bytebelt:latest
 
       - name : Test for docker-compose file
-        run: docker-compose up -d
+        run: |
+          cd ./bytebelt/
+          docker-compose up -d
+          sleep 30
+          site_online=$(curl -o /dev/null -s -w "%{http_code}\n" http://localhost:8000)
+          if [[ "$site_online" =~ ^4 ]] || [[ "$site_online" =~ ^5 ]]; then
+            echo "Test Failed $site_online"
+            exit 1
+          else
+            echo "Test Ok $site_online"
+          fi
